#!/bin/bash

# @browserify: convert jsx to js file(s).
#
# @$1, first passed-in argument from command ($0 is the filename)


# Pre-Pathing: allow 'browserify' command
PATH="/usr/local/bin:$PATH"


# track execution of script
log_file="$1"/log/webcompiler/browserify.log
set -x;
exec &> >(while read -r line; do
  log_date=$(date +%Y-%m-%d:%H:%M:%S)
  printf "%s %s\n" "[$log_date]" "$line" >> "$log_file"
done)

# create empty '.gitignore'
cat /dev/null > "$1"/src/js/.gitignore


# watch '[root_dir]/src/jsx/' subdirectory
inotifywait "$1"/src/jsx/ -m -r -e close_write -e move |

  # convert with 'browserify'
  (cd /usr/lib/node_modules && browserify "$1"/src/jsx/content.jsx -t [ babelify --presets latest,stage-2,react ] -o "$1"/src/js/content.js)

  # append file to '.gitignore'
  fgrep -q content.js "$1"/src/js/.gitignore || echo content.js >> "$1"/src/js/.gitignore
