#!/bin/bash

# @sass: minify scss file(s).
#
# @$1, first passed-in argument from command ($0 is the filename)


# Pre-Pathing: allow 'sass' command
PATH="/usr/local/bin:$PATH"


# allow globstar, and extglob patterns
shopt -s globstar extglob


# track execution of script
log_file=/vagrant/log/webcompiler/sass_copy.log
set -x;

# watch '[root_dir]/interface/static/css/' subdirectory
inotifywait /vagrant/interface/static/css/ -m -r -e close_write -e move --format %w%f |

  # ensure proper file extension: on successive builds
  while read -r file; do

    if [ -f "$file" ] && [[ $file = !(*.min).css ]]; then
      mv "$file" "${file/%.css/.min.css}"
    fi

  done
