#!/bin/bash

# @sass: minify scss file(s).
#
# @$1, first passed-in argument from command ($0 is the filename)
# @$2, second passed-in argument from command


# Pre-Pathing: allow 'sass' command
PATH="/usr/local/bin:$PATH"


# track execution of script
log_file="$1"/log/webcompiler/sass.log
set -x;
exec &> >(while read -r line; do
  log_date=$(date +%Y-%m-%d:%H:%M:%S)
  printf "%s %s\n" "[$log_date]" "$line" >> "$log_file"
done)

# watch '[root_dir]/src/scss/' subdirectory
inotifywait "$1"/src/scss/ -m -r -e close_write -e move |

  # compile with 'scss'
  (node-sass "$1"/src/scss/style.scss "$1"/interface/static/css/style.min.css --output-style compressed)
