#!/bin/bash

# @uglifyjs: minify javascript file(s).
#
# @$1, first passed-in argument from command ($0 is the filename)

# Pre-Pathing: allow 'uglifyjs' command
PATH="/usr/local/bin:$PATH"


# track execution of script
log_file="$1"/log/webcompiler/uglifyjs.log
set -x;
exec &> >(while read -r line; do
  log_date=$(date +%Y-%m-%d:%H:%M:%S)
  printf "%s %s\n" "[$log_date]" "$line" >> "$log_file"
done)

# watch '[root_dir]/src/js/' subdirectory
inotifywait "$1"/src/js/ -m -r -e close_write -e move --format %f |

  # Minify Javascript
  while read -r file; do

    # get last `.` occurence as starting extension
    extension=${file##*.}
    # filename (without 'last' extension)
    filename="${file%.*}"

    if [ "$extension" = 'js' ]; then

      # minifiy with 'uglifyjs'
      uglifyjs -c --output "$1/interface/static/js/$filename".min.js "$1/src/js/$file"

    fi
  done
