#!/bin/bash 

# remove containers, images, and networks
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
docker rmi -f $(docker images -q)
docker network rm app_nw

# build containers
docker build -f default.dockerfile -t container-default .
docker build -f database.dockerfile -t container-database .
docker build -f webserver.dockerfile -t container-webserver .

# run containers within common network
if [ "$(uname -s)" == 'Linux' ]; then
  docker network create -d bridge app_nw && docker run --name base --net=app_nw -d container-default && docker run --name database --net=app_nw -d container-database && docker run --name webserver --net=app_nw -d container-webserver test
else
  winpty docker network create -d bridge app_nw && winpty docker run --name base --net=app_nw -d container-default && winpty docker run --name database --net=app_nw -d container-database && winpty docker run --name webserver --net=app_nw -d container-webserver test
fi