#!/bin/bash

RANCHER_VERSION='v0.12.5-rc1'
RANCHER_REPO='https://github.com/rancher/rancher-compose'
CURRENT_DISTRO=$(uname -s)

case "${CURRENT_DISTRO}" in
    Linux*)
        DISTRO_TYPE='linux'
        RANCHER_DISTRO='rancher-compose-linux-amd64';;
    Darwin*)
        DISTRO_TYPE='unix'
        RANCHER_DISTRO='rancher-compose-darwin-amd64';;
    CYGWIN*)
        DISTRO_TYPE='windows'
        RANCHER_DISTRO='rancher-compose-windows-amd64';;
    MINGW*)
        DISTRO_TYPE='windows'
        RANCHER_DISTRO='rancher-compose-windows-amd64';;
    *)
        echo 'Error: distro is not known, contact repository owner.'
        exit 1
esac

## download rancher-compose
if [ "$DISTRO_TYPE" = 'unix' ]; then
    curl -OL "$RANCHER_REPO/releases/download/$RANCHER_VERSION/$RANCHER_DISTRO-$RANCHER_VERSION.tar.gz"
    tar zxf "$RANCHER_DISTRO-$RANCHER_VERSION.tar.gz"
    rm "$RANCHER_DISTRO-$RANCHER_VERSION.tar.gz"
    sudo mv rancher-compose-v"$RANCHER_VERSION"/rancher-compose /usr/local/bin/rancher-compose
    sudo chmod +x /usr/local/bin/rancher-compose

elif [ "$DISTRO_TYPE" = 'linux' ]; then
    if [ ! $(which wget) ]; then
        sudo apt-get -y install wget || sudo yum -y install wget || echo 'wget cannot install' && exit 1
    fi

    wget "$RANCHER_REPO/releases/download/$RANCHER_VERSION/$RANCHER_DISTRO-$RANCHER_VERSION.tar.gz"
    tar zxf "$RANCHER_DISTRO-$RANCHER_VERSION.tar.gz"
    rm "$RANCHER_DISTRO-$RANCHER_VERSION.tar.gz"
    sudo mv rancher-compose-v"$RANCHER_VERSION"/rancher-compose /usr/local/bin/rancher-compose
    sudo chmod +x /usr/local/bin/rancher-compose

elif [ "$DISTRO_TYPE" = 'windows' ]; then
    curl -OL "$RANCHER_REPO/releases/download/$RANCHER_VERSION/$RANCHER_DISTRO-$RANCHER_VERSION.zip"
    unzip -j "$RANCHER_DISTRO-$RANCHER_VERSION"
    mv -f rancher-compose.exe /c/Users/$(whoami)/bin
    rm "$RANCHER_DISTRO-$RANCHER_VERSION.zip"

else
    echo 'Error: distro is not known, contact repository owner.'
    exit 1
fi

## install rancher ecosystem
if docker -v >/dev/null 2>&1; then
    docker run -d --restart=unless-stopped -p 8080:8080 rancher/server

    mkdir -p ./docker_storage_redis
    mkdir -p ./docker_storage_mongodb
    mkdir -p ./docker_storage_mariadb

    rancher-compose up -f docker-compose.development -r rancher-compose.development
else
    echo 'please install docker per https://github.com/jeff1evesque/machine-learning#installation'
    exit 1
fi
