#!/bin/bash

RANCHER_VERSION='v0.12.5-rc1'
RANCHER_REPO='https://github.com/rancher/rancher-compose'
CURRENT_DISTRO=$(uname -s)

case "${CURRENT_DISTRO}" in
    Linux*)
        DISTRO_TYPE='linux'
        RANCHER_DISTRO='rancher-compose-linux-amd64';;
    Darwin*)
        DISTRO_TYPE='unix'
        RANCHER_DISTRO='rancher-compose-darwin-amd64';;
    CYGWIN*)
        DISTRO_TYPE='windows'
        RANCHER_DISTRO='rancher-compose-windows-amd64';;
    MINGW*)
        DISTRO_TYPE='windows'
        RANCHER_DISTRO='rancher-compose-windows-amd64';;
    *)
        echo 'Error: distro is not known, contact repository owner.'
        exit 1
esac

## download rancher-compose
if [ "$DISTRO_TYPE" = 'unix' ]; then
    curl -OL "$RANCHER_REPO/releases/download/$RANCHER_VERSION/$RANCHER_DISTRO-$RANCHER_VERSION.tar.gz"
    tar zxf "$RANCHER_DISTRO-$RANCHER_VERSION.tar.gz"
    rm "$RANCHER_DISTRO-$RANCHER_VERSION.tar.gz"
    sudo mv rancher-compose-v"$RANCHER_VERSION"/rancher-compose /usr/local/bin/rancher-compose
    sudo chmod +x /usr/local/bin/rancher-compose

elif [ "$DISTRO_TYPE" = 'linux' ]; then
    if [ ! which curl ]; then
        sudo apt-get -y install curl || sudo yum -y install curl || (echo 'curl cannot install' && exit 1)
    fi

    curl -OL "$RANCHER_REPO/releases/download/$RANCHER_VERSION/$RANCHER_DISTRO-$RANCHER_VERSION.tar.gz"
    tar zxf "$RANCHER_DISTRO-$RANCHER_VERSION.tar.gz"
    rm "$RANCHER_DISTRO-$RANCHER_VERSION.tar.gz"
    sudo mv rancher-compose-v"$RANCHER_VERSION"/rancher-compose /usr/local/bin/rancher-compose
    sudo chmod +x /usr/local/bin/rancher-compose

elif [ "$DISTRO_TYPE" = 'windows' ]; then
    curl -OL "$RANCHER_REPO/releases/download/$RANCHER_VERSION/$RANCHER_DISTRO-$RANCHER_VERSION.zip"
    unzip -j "$RANCHER_DISTRO-$RANCHER_VERSION"
    mv -f rancher-compose.exe /c/Users/$(whoami)/bin
    rm "$RANCHER_DISTRO-$RANCHER_VERSION.zip"

else
    echo 'Error: distro is not known, contact repository owner.'
    exit 1
fi

## install rancher ecosystem
if docker -v >/dev/null 2>&1; then
    docker run -d --restart=unless-stopped -p 8080:8080 rancher/server

    mkdir -p ./docker_storage_redis
    mkdir -p ./docker_storage_mongodb
    mkdir -p ./docker_storage_mariadb

    SERVER_IP=$(docker-machine ip default)

    ## generate access + secret key:
    ##
    ## Note: exporting environment eliminates the need to explicitly provide
    ##       environment variable explicitly to 'rancher-compose' command.
    ##
    ACCESS=$(
        curl -v -X POST -H 'Accept: application/json' \
        -H 'Content-Type: application/json' \
        -d '{"type":"apikey","accountId":"1a5","name":"admin","description":null,"created":null,"kind":null,"removed":null,"uuid":null}' \
		http://"$SERVER_IP":8080/v1/projects/1a5/apikey
    )

    if [ "$DISTRO_TYPE" = 'unix' ] || [ "$DISTRO_TYPE" == 'linux' ]; then
        export RANCHER_ACCESS_KEY=$(cat "$ACCESS" | python -c 'import json,sys;json.load(sys.stdin);print obj["name"]')
        export RANCHER_SECRET_KEY=$(cat "$ACCESS" | python -c 'import json,sys;obj=json.load(sys.stdin);print(obj["secretValue"]')
    else
        export RANCHER_ACCESS_KEY=$(
            powershell -Command "\$API=(invoke-webrequest http://$SERVER_IP:8080 | ConvertFrom-JSON); return \$API.name"
        )
        export RANCHER_SECRET_KEY=$(
            powershell -Command "\$API=(invoke-webrequest http://$SERVER_IP:8080 | ConvertFrom-JSON); return \$API.secretValue"
        )
    fi
    export RANCHER_URL=http://"$SERVER_IP":8080/

    ## notify access + secret key
    echo "RANCHER_ACCESS_KEY: $RANCHER_ACCESS_KEY" > ./rancher-auth.txt
    echo "RANCHER_SECRET_KEY: $RANCHER_SECRET_KEY" >> ./rancher-auth.txt
    echo 'Access and secret generated in ./rancher-auth.txt'

    rancher --url "http://$SERVER_IP:8080 --access-key $RANCHER_ACCESS_KEY --secret-key $RANCHER_SECRET_KEY"
    rancher-compose -f docker-compose.development -r rancher-compose.development up
else
    echo 'please install docker per https://github.com/jeff1evesque/machine-learning#installation'
    exit 1
fi
