#!/usr/bin/env ruby
#^syntax detection

## Declare puppet module repository
forge "https://forge.puppetlabs.com"

## Install Module: stdlib (apt dependency)
mod 'stdlib',
  :git => "https://github.com/puppetlabs/puppetlabs-stdlib",
  :ref => "4.6.0"

## Install Module: apt (from master)
mod 'apt',
  :git => "https://github.com/puppetlabs/puppetlabs-apt"

## Install Module: nodejs
mod 'nodejs',
  :git => "https://github.com/puppet-community/puppet-nodejs",
  :ref => "1.1.0"

## Install Module: git
mod 'git',
  :git => "https://github.com/puppetlabs/puppetlabs-git",
  :ref => "0.4.0"

## Install Module: vcsrepo
mod 'vcsrepo',
  :git => "https://github.com/puppetlabs/puppetlabs-vcsrepo",
  :ref => "1.3.0"

## Install Module: mysql (to be used for mariadb)
mod 'mysql',
  :git => "https://github.com/puppetlabs/puppetlabs-mysql",
  :ref => "3.4.0"

## Install Module: sys (required for heredoc logic in 'start_webserver.pp')
mod 'sys',
  :git => "https://github.com/counsyl/puppet-sys",
  :ref => "0.9.18"

## Install Module: python (from master), which includes pip, devel,
#                  flask, requests, pipx (enhanced pip).
mod 'python',
  :git => "https://github.com/counsyl/puppet-python"

## Install Module: timezone
mod 'timezone',
  :git => "https://github.com/BashtonLtd/puppet-timezone",
  :ref => "v0.1.3"

## Install Module: nginx
mod 'nginx',
  :git => "https://github.com/jfryman/puppet-nginx",
  :ref => "v0.2.7"

## Install Module: uwsgi (from master)
mod 'uwsgi',
  :git => https://github.com/vaijab/puppet-uwsgi"