#!/usr/bin/env ruby
## Install Module: stdlib (apt dependency)
mod 'stdlib',
  :git => "git@github.com:puppetlabs/puppetlabs-stdlib.git",
  :ref => "4.6.0"

## Install Module: apt (from master)
mod 'apt',
  :git => "git@github.com:puppetlabs/puppetlabs-apt.git"

## Install Module: nodejs
mod 'nodejs',
  :git => "git@github.com:puppet-community/puppet-nodejs.git",
  :ref => "1.1.0"

## Install Module: git
mod 'git',
  :git => "git@github.com:puppetlabs/puppetlabs-git.git",
  :ref => "0.4.0"

## Install Module: vcsrepo
mod 'vcsrepo',
  :git => "git@github.com:puppetlabs/puppetlabs-vcsrepo.git",
  :ref => "1.3.0"

## Install Module: mysql (to be used for mariadb)
mod 'mysql',
  :git => "git@github.com:puppetlabs/puppetlabs-mysql.git",
  :ref => "3.4.0"

## Install Module: sys (required for heredoc logic in 'start_webserver.pp')
mod 'sys',
  :git => "git@github.com:counsyl/puppet-sys.git",
  :ref => "0.9.18"

## Install Module: python (from master), which includes pip, devel,
#                  flask, requests, pipx (enhanced pip).
mod 'python',
  :git => "git@github.com:counsyl/puppet-python.git"

## Install Module: nginx
mod 'nginx',
  :git => "git@github.com:jfryman/puppet-nginx.git",
  :ref => "v0.2.7"

## Install Module: uwsgi (from master)
mod 'uwsgi',
  :git => "git@github.com:vaijab/puppet-uwsgi.git"

## Install Module: timezone
mod 'timezone',
  :git => "git@github.com:BashtonLtd/puppet-timezone.git",
  :ref => "v0.1.3"
