#!/bin/bash

# @browserify: convert jsx to js file(s).


# Pre-Pathing: allow 'browserify' command
PATH="/usr/local/bin:$PATH"


# track execution of script
set -x; exec > /vagrant/log/browserify_execution.log 2>&1


# watch '/vagrant/src/jsx/' subdirectory
inotifywait /vagrant/src/jsx/ -m -e close_write -e move --format %f |
    # Convert JSX to JS
    while read -r file; do
      # get last `.` occurence as starting extension
      extension=${file##*.}
      # filename (without 'last' extension)
      filename="${file%.*}"

      if [ "$extension" = 'jsx' ]
      then

        # convert with 'browserify'
        (cd /usr/lib/node_modules && browserify /vagrant/src/jsx/"$file" -t [ babelify --presets es2015,react ] -o /vagrant/src/js/"$filename".js)

      fi
    done
  fi
