#!/usr/bin/env ruby
## Install Module: stdlib (apt dependency)
mod 'stdlib',
  :git => "https://github.com/puppetlabs/puppetlabs-stdlib.git",
  :ref => "4.6.0"

## Install Module: apt (from master)
mod 'apt',
  :git => "https://github.compuppetlabs/puppetlabs-apt.git"

## Install Module: nodejs
mod 'nodejs',
  :git => "https://github.compuppet-community/puppet-nodejs.git",
  :ref => "1.1.0"

## Install Module: git
mod 'git',
  :git => "https://github.compuppetlabs/puppetlabs-git.git",
  :ref => "0.4.0"

## Install Module: vcsrepo
mod 'vcsrepo',
  :git => "https://github.compuppetlabs/puppetlabs-vcsrepo.git",
  :ref => "1.3.0"

## Install Module: mysql (to be used for mariadb)
mod 'mysql',
  :git => "https://github.compuppetlabs/puppetlabs-mysql.git",
  :ref => "3.4.0"

## Install Module: sys (required for heredoc logic in 'start_webserver.pp')
mod 'sys',
  :git => "https://github.comcounsyl/puppet-sys.git",
  :ref => "0.9.18"

## Install Module: python (from master), which includes pip, devel,
#                  flask, requests, pipx (enhanced pip).
mod 'python',
  :git => "https://github.comcounsyl/puppet-python.git"

## Install Module: timezone
mod 'timezone',
  :git => "https://github.comBashtonLtd/puppet-timezone.git",
  :ref => "v0.1.3"
