#!/bin/bash

# @web_scss: minify scss file(s).


# Pre-Pathing: allow 'sass' command
PATH="/usr/local/bin:$PATH"


# track execution of script
set -x; exec > /vagrant/log/sass_execution.log 2>&1


# watch '/vagrant/src/scss/' subdirectory
inotifywait /vagrant/src/scss/ -m -e close_write -e move --format %f |
  # Compile CSS
  while read -r file; do
    # filename (without 'last' extension)
    filename="${file%.*}"

    # compile with 'sass'
    node-sass /vagrant/src/scss/"$file" /vagrant/interface/static/css/"$filename".min.css --output-style compressed
  done
