#!/bin/bash

# @web_js: is executed from 'bash_loader', which is why the directory
#          paths seem shorter in this file (i.e. missing extra '../').


# Pre-Pathing: allow 'uglifyjs' command
PATH="/usr/local/bin:$PATH"


# track execution of script
set -x; exec > /vagrant/log/uglifyjs_execution.log 2>&1


# watch '/vagrant/src/js/' subdirectory
inotifywait /vagrant/src/js/ -m -e close_write -e move -e create |
  # Minify Javascript
  while read path action file; do
    # filename (without 'last' extension)
    filename="${file%.*}"

    # minifiy with 'uglifyjs'
    uglifyjs -c --output /vagrant/web_interface/static/js/"$filename".min.js /vagrant/src/js/"$file"
  done
