#!/usr/bin/env ruby

## @Puppetfile: this file is intended for travis ci implementation.

mod 'stdlib',
  :git => 'https://github.com/puppetlabs/puppetlabs-stdlib.git',
  :ref => '4.25.1'

mod 'apt',
  :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
  :ref => '4.5.1'

mod 'mysql',
  :git => 'https://github.com/puppetlabs/puppetlabs-mysql.git',
  :ref => '3.4.0'

mod 'sys',
  :git => 'https://github.com/counsyl/puppet-sys.git',
  :ref => '0.9.18'

## includes pip, devel, flask, requests, pipx (enhanced pip).
mod 'python',
  :git => 'https://github.com/counsyl/puppet-python.git',
  :ref => '0.9.9'

mod 'timezone',
  :git => 'https://github.com/BashtonLtd/puppet-timezone.git',
  :ref => '2.0.0'

mod 'concat',
  :git => 'https://github.com/puppetlabs/puppetlabs-concat.git',
  :ref => '4.2.1'

mod 'nginx',
  :git => 'https://github.com/voxpupuli/puppet-nginx.git',
  :ref => 'v0.11.0'