#!/usr/bin/env ruby

## @Puppetfile: this file is intended for travis ci implementation.

mod 'stdlib',
  :git => 'https://github.com/puppetlabs/puppetlabs-stdlib.git',
  :ref => '4.15.0'

mod 'apt',
  :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
  :ref => '4.4.1'

mod 'nodejs',
  :git => 'https://github.com/voxpupuli/puppet-nodejs.git',
  :ref => 'v4.0.1'

mod 'git',
  :git => 'https://github.com/puppetlabs/puppetlabs-git.git',
  :ref => '0.4.0'

mod 'vcsrepo',
  :git => 'https://github.com/puppetlabs/puppetlabs-vcsrepo.git',
  :ref => '1.3.0'

mod 'mysql',
  :git => 'https://github.com/puppetlabs/puppetlabs-mysql.git',
  :ref => '3.4.0'

mod 'sys',
  :git => 'https://github.com/counsyl/puppet-sys.git',
  :ref => '0.9.18'

## includes pip, devel, flask, requests, pipx (enhanced pip).
mod 'python',
  :git => 'https://github.com/counsyl/puppet-python.git',
  :ref => '0.9.9'

mod 'timezone',
  :git => 'https://github.com/BashtonLtd/puppet-timezone.git',
  :ref => '2.0.0'

mod 'concat',
  :git => 'https://github.com/puppetlabs/puppetlabs-concat.git',
  :ref => '2.2.0'
