#!/usr/bin/env ruby

## @Puppetfile, any changes to this file, should be made correspondingly with
##      the /puppet/scripts/Puppetfile file.
##
## Note: /puppet/scripts/Puppetfile is used for the travis ci implementation.

## Install Module: stdlib (apt dependency)
mod 'stdlib',
  :git => 'git@github.com:puppetlabs/puppetlabs-stdlib.git',
  :ref => '4.15.0'

## Install Module: apt (from master)
mod 'apt',
  :git => 'git@github.com:puppetlabs/puppetlabs-apt.git',
  :ref => '2.3.0'

## Install Module: mongodb
mod 'mongodb',
  :git => 'git@github.com:puppetlabs/puppetlabs-mongodb.git',
  :ref => '0.17.0'
