##
## This file contains database related configurations:
##
##  - mongodb
##  - mariadb
##
## @host, @hostname, defined from executed 'docker' command.
##
database:
    mariadb:
        bind_address: '0.0.0.0'
        host: 'mariadb'
        allow_host: '%'
        name: 'db_machine_learning'
        provisioner: 'provisioner'
        provisioner_password: 'password'
        username: 'authenticated'
        password: 'password'
        tester: 'tester'
        tester_password: 'password'
        root_password: 'password'
        log_path: '/log/database'

    mongodb:
        hostname: 'mongodb'
        name: 'dataset'
        username: 'authenticated'
        password: 'password'
        keyserver = 'hkp://keyserver.ubuntu.com:80'
        mongodb_key = '0C49F3730359A14518585931BC711F9BA15703C6'
        source_list: 'deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse'

        storage:
            dbPath: /var/lib/mongodb
            journal:
                enabled: true

        systemLog:
            verbosity: 1
            destination: file
            logAppend: true
            systemLogPath: '/var/log/mongodb/mongod.log'

        net:
            port: 27017
            bindIp: 0.0.0.0

        processManagement:
            pidfilepath: '/var/run/mongod.pid'


        security:
            authorization: 'enabled'
