#!/bin/bash

## variables
##
## @PUPPETSERVER_FQDN, this needs match the result of running the 'hostnamectl' command
##     from the environment running the puppetserver / puppetmaster.
##
## @PUPPETSERVER_IP, address that corresponds to the puppetserver.
##

## local variables
PUPPETSERVER_FQDN="$1"
PUPPETSERVER_IP="$2"
HOSTNAME="$3"

## set fqdn
sudo sh -c "echo \"$PUPPETSERVER_IP  $PUPPETSERVER_FQDN\" >> /etc/hosts"

## set hostname
sudo hostname "$HOSTNAME"
sudo sh -c "echo \"$HOSTNAME\" > /etc/hostname"

## restart network
sudo ifdown eth0 && sudo ifup eth0
