#!/usr/bin/env ruby

## @Puppetfile, any changes to this file, should be made correspondingly with
#      the /puppet/scripts/Puppetfile file.
#
#  Note: /puppet/scripts/Puppetfile is used for the travis ci implementation.

## Install Module: stdlib (apt dependency)
mod 'stdlib',
  :git => 'git@github.com:puppetlabs/puppetlabs-stdlib.git',
  :ref => '4.15.0'

## Install Module: apt (from master)
mod 'apt',
  :git => 'git@github.com:puppetlabs/puppetlabs-apt.git',
  :ref => '2.3.0'

## Install Module: nodejs
mod 'nodejs',
  :git => 'git@github.com:voxpupuli/puppet-nodejs.git',
  :ref => 'v2.3.0'

## Install Module: git
mod 'git',
  :git => 'git@github.com:puppetlabs/puppetlabs-git.git',
  :ref => '0.4.0'

## Install Module: vcsrepo
mod 'vcsrepo',
  :git => 'git@github.com:puppetlabs/puppetlabs-vcsrepo.git',
  :ref => '1.3.0'

## Install Module: mysql (to be used for mariadb)
mod 'mysql',
  :git => 'git@github.com:puppetlabs/puppetlabs-mysql.git',
  :ref => '3.4.0'

## Install Module: sys (required for heredoc logic in 'start_webserver.pp')
mod 'sys',
  :git => 'git@github.com:counsyl/puppet-sys.git',
  :ref => '0.9.18'

## Install Module: python (from master), which includes pip, devel,
#                  flask, requests, pipx (enhanced pip).
mod 'python',
  :git => 'git@github.com:counsyl/puppet-python.git',
  :ref => '0.9.9'

## Install Module: timezone
mod 'timezone',
  :git => 'git@github.com:BashtonLtd/puppet-timezone.git',
  :ref => 'v0.1.3'

## Install Module: concat
mod 'concat',
  :git => 'git@github.com:puppetlabs/puppetlabs-concat.git',
  :ref => '2.2.0'

## Install Module: nginx
mod 'nginx',
  :git => 'git@github.com:voxpupuli/puppet-nginx.git',
  :ref => 'v0.5.0'
