#!/bin/bash

# @browserify: convert jsx to js file(s).
#
# @$1, first passed-in argument from command ($0 is the filename)


# Pre-Pathing: allow 'browserify' command
PATH="/usr/local/bin:$PATH"


cd "$1"/src/jsx && for file in *; do
  # filename (without 'last' extension)
  filename="${file%.*}"
  # get last `.` occurence as starting extension
  file_extension="${file##*.}"

  if [ "$file_extension" = 'jsx' ]; then

    # convert with 'browserify'
    (cd /usr/lib/node_modules && browserify "$1/src/jsx/$file" -t [ babelify --presets es2015,es2016,es2017,react ] -o "$1/src/js/$filename.js")

    # append file to '.gitignore'
    fgrep -q "$filename".js "$1"/src/js/.gitignore || echo "$filename".js >> "$1"/src/js/.gitignore

  fi
done
