#!/bin/bash

# @imagemin: minify image file(s).
#
# @$1, first passed-in argument from command ($0 is the filename)
#
# Note: minifid GIF files lose their animated quality. This script minifies
#       all images except GIF (copied to the 'asset/').


# Pre-Pathing: allow 'imagemin' command
PATH="/usr/local/bin:$PATH"


# docker container
cd "$1"/src/img && for file in *; do
  # filename (without directory path)
  filename="${file##*/}"
  # get last `.` occurence as starting extension
  file_extension="${file##*.}"

  # minify with 'imagemin'
  if [ "$file_extension" = 'gif' ] || [ "$file_extension" = 'svg' ]; then
    cp "$1/src/img/$file" "$1/interface/static/img/$filename"
  else
    imagemin "$1/src/img/$file" > "$1/interface/static/img/$filename" &
  fi
done