#!/bin/bash

# @sass: minify scss file(s).
#
# @$1, first passed-in argument from command ($0 is the filename)


# Pre-Pathing: allow 'sass' command
PATH="/usr/local/bin:$PATH"


cd "$1"/src/scss && for file in *; do
  # get last `.` occurence as starting extension
  extension=${file##*.}
  # filename (without 'last' extension)
  filename="${file%.*}"

  if [ "$extension" = 'scss' ] && [ "${file:0:1}" != '_' ]
  then

    # compile with 'scss'
    node-sass "$1/src/scss/$file" "$1/interface/static/css/$filename".min.css --output-style compressed

  fi
done
