#!/bin/bash

# @sass: minify scss file(s).
#
# @$1, first passed-in argument from command ($0 is the filename)


# Pre-Pathing: allow 'sass' command
PATH="/usr/bin:$PATH"


cd "$1"/src/scss && for file in *; do
  # get last `.` occurence as starting extension
  extension=${file##*.}

  if [ "$extension" = 'scss' ] && [ "${file:0:1}" != '_' ]; then

    # compile with 'node-sass'
    node-sass "$1"/src/scss/style.scss "$1"/interface/static/css/style.css

  fi
done
