#!/bin/bash

# @browserify: convert jsx to js file(s).
#
# @$1, first passed-in argument from command ($0 is the filename)


# Pre-Pathing: allow 'browserify' command
PATH="/usr/local/bin:$PATH"


cd "$1"/src/jsx && for file in *; do
  # get last `.` occurence as starting extension
  file_extension="${file##*.}"

  if [ "$file_extension" = 'jsx' ]; then

    # convert with 'browserify'
    (cd /usr/lib/node_modules && browserify "$1"/src/jsx/content.jsx -t [ babelify --presets env,stage-2,react ] -o "$1"/src/js/content.js)

    # append file to '.gitignore'
    grep -qF content.js "$1"/src/js/.gitignore || echo content.js >> "$1"/src/js/.gitignore

  fi
done
