#!/bin/bash

# create 'log' directory if doesn't exist
mkdir -p ../log

# trace last execution of 'bash_loader'
set -x; exec > ../log/log_bash_loader 2>&1

# allow @(var) syntax
shopt -s extglob

# predetermined directories: haystack = ( ./@(directory1|directory2|directory3)/* )
haystack=(./@(build)/*)

# record 'haystack' variable in 'logs/log_bash_loader'
true "${haystack[@]}"

# execute scripts in 'haystack'
for file in "${haystack[@]}"; do
 ./"$file" &
done
