#!/bin/bash

# @browserify: convert jsx to js file(s).


# Pre-Pathing: allow 'browserify' command
PATH="/usr/local/bin:$PATH"


# track execution of script
log=/vagrant/log/webcompiler/uglifyjs.log
date=$(date +%Y-%m-%d:%H:%M:%S)
set -x;
exec &> >(while read -r line; do printf "$date $line" >> "$log"; done;)


# create empty '.gitignore'
cat /dev/null > /vagrant/src/js/.gitignore


# watch '/vagrant/src/jsx/' subdirectory
inotifywait /vagrant/src/jsx/ -m -e close_write -e move --format %f |
    # Convert JSX to JS
    while read -r file; do
      # filename (without 'last' extension)
      filename="${file%.*}"
      # get last `.` occurence as starting extension
      file_extension="${file##*.}"

      if [ "$file_extension" = 'jsx' ]
      then

        # convert with 'browserify'
        (cd /usr/lib/node_modules && browserify /vagrant/src/jsx/"$file" -t [ babelify --presets es2015,react ] -o /vagrant/src/js/"$filename".js)

        # append file to '.gitignore'
        fgrep -q "$filename".js /vagrant/src/js/.gitignore || echo "$filename".js >> /vagrant/src/js/.gitignore

      fi
    done
