#!/bin/bash

# @browserify: convert jsx to js file(s).
#
# @$1, first passed-in argument from command ($0 is the filename)


# Pre-Pathing: allow 'browserify' command
PATH="/usr/local/bin:$PATH"


# docker container
if [ "$1" = "/var/machine-learning" ]; then
  echo 'test' >> "$1/src/jsx/one.txt"
  cd "$1"/src/jsx && for file in *; do
    # filename (without 'last' extension)
    filename="${file%.*}"
    # get last `.` occurence as starting extension
    file_extension="${file##*.}"

    echo "file: $file" >> "$1/src/jsx/two.txt"
    echo "filename: $filename" >> "$1/src/jsx/two.txt"
    echo "file_extension: $file_extension" >> "$1/src/jsx/two.txt"

    if [ "$file_extension" = 'jsx' ]
    then
      echo 'test' >> "$1/src/jsx/three.txt"
      # convert with 'browserify'
      cd /usr/lib/node_modules && browserify "$1/src/jsx/$file" -t [ babelify --presets es2015,react ] -o "$1/src/js/$filename.js"

      # append file to '.gitignore'
      fgrep -q "$filename".js "$1"/src/js/.gitignore || echo "$filename".js >> "$1"/src/js/.gitignore

    fi
  done

# vagrant container
else
  # track execution of script
  log_file="$1"/log/webcompiler/browserify.log
  set -x;
  exec &> >(while read -r line; do
    log_date=$(date +%Y-%m-%d:%H:%M:%S)
    printf "%s %s\n" "[$log_date]" "$line" >> "$log_file"
  done)

  # create empty '.gitignore'
  cat /dev/null > "$1"/src/js/.gitignore


  # watch '[root_dir]/src/jsx/' subdirectory
  inotifywait "$1"/src/jsx/ -m -e close_write -e move --format %f |
    # Convert JSX to JS
    while read -r file; do
      # filename (without 'last' extension)
      filename="${file%.*}"
      # get last `.` occurence as starting extension
      file_extension="${file##*.}"

      if [ "$file_extension" = 'jsx' ]
      then

        # convert with 'browserify'
        (cd /usr/lib/node_modules && browserify "$1/src/jsx/$file" -t [ babelify --presets es2015,react ] -o "$1/src/js/$filename.js")

        # append file to '.gitignore'
        fgrep -q "$filename".js "$1"/src/js/.gitignore || echo "$filename".js >> "$1"/src/js/.gitignore

      fi
    done
fi
