#!/bin/bash

# @imagemin: minify image file(s).
#
# Note: minifid GIF files lose their animated quality. This script minifies
#       all images except GIF (copied to the 'asset/').


# Pre-Pathing: allow 'imagemin' command
PATH="/usr/local/bin:$PATH"


# track execution of script
log_file=/vagrant/log/webcompiler/imagemin.log
log_date=$(date +%Y-%m-%d:%H:%M:%S)
set -x;
exec &> >(while read -r line
  do printf "%s %s\n" "$log_date" "$line" >> "$log_file"
done)


# watch '/vagrant/src/img/' subdirectory
inotifywait /vagrant/src/img/ -m -e close_write -e move --format %f |
  # Minify Images
  while read -r file; do
    # filename (without directory path)
    filename="${file##*/}"
    # get last `.` occurence as starting extension
    file_extension="${file##*.}"

    # minify with 'imagemin'
    if [ "$file_extension" = 'gif' ]; then
      cp /vagrant/src/img/"$file" /vagrant/interface/static/img/"$filename"
    else
      imagemin /vagrant/src/img/"$file" > /vagrant/interface/static/img/"$filename" &
    fi
  done
