#!/bin/bash

# @sass: minify scss file(s).


# Pre-Pathing: allow 'sass' command
PATH="/usr/local/bin:$PATH"


# track execution of script
log=/vagrant/log/webcompiler/sass.log
date=$(date +%Y-%m-%d:%H:%M:%S)
set -x;
exec &> >(while read -r line; do printf "%s %s" "$date $line" >> "$log"; done;)


# watch '/vagrant/src/scss/' subdirectory
inotifywait /vagrant/src/scss/ -m -e close_write -e move --format %f |
  # Compile CSS
  while read -r file; do
    # get last `.` occurence as starting extension
    extension=${file##*.}
    # filename (without 'last' extension)
    filename="${file%.*}"

    if [ "$extension" = 'scss' ] && [ "${file:0:1}" != '_' ]
    then

      # compile with 'scss'
      node-sass /vagrant/src/scss/"$file" /vagrant/interface/static/css/"$filename".min.css --output-style compressed

    fi
  done
