#!/bin/bash

# @uglifyjs: minify javascript file(s).
#
# @$1, first passed-in argument from command ($0 is the filename)

# Pre-Pathing: allow 'uglifyjs' command
PATH="/usr/local/bin:$PATH"

echo 'test' >> /var/machine-learning/interface/static/js/one.txt

# track execution of script

echo 'test' >> /var/machine-learning/interface/static/js/two.txt

# docker container
if [ "$1" = "/var/machine-learning" ]; then
  echo 'test' >> /var/machine-learning/interface/static/js/three.txt
# vagrant container
else
  echo 'test' >> /var/machine-learning/interface/static/js/four.txt
fi
