#!/bin/bash

# @uglifyjs: minify javascript file(s).


# Pre-Pathing: allow 'uglifyjs' command
PATH="/usr/local/bin:$PATH"


# track execution of script
log=/vagrant/log/webcompiler/uglifyjs.log
date=$(date +%Y-%m-%d:%H:%M:%S)
set -x;
exec &> >(while read -r line
  do printf "%s %s" "$date" "$line" >> "$log"
done)


# watch '/vagrant/src/js/' subdirectory
inotifywait /vagrant/src/js/ -m -e close_write -e move --format %f |
  # Minify Javascript
  while read -r file; do

      # get last `.` occurence as starting extension
      extension=${file##*.}
      # filename (without 'last' extension)
      filename="${file%.*}"

      if [ "$extension" = 'js' ]
      then

        # minifiy with 'uglifyjs'
        uglifyjs -c --output /vagrant/interface/static/js/"$filename".min.js /vagrant/src/js/"$file"

      fi
  done
