#!/bin/bash

# @uglifyjs: minify javascript file(s).


# Pre-Pathing: allow 'uglifyjs' command
PATH="/usr/local/bin:$PATH"


# track execution of script
set -x; exec > /vagrant/log/webcompiler/uglifyjs_execution.log 2>&1


# watch '/vagrant/src/js/' subdirectory
inotifywait /vagrant/src/js/ -m -e close_write -e move --format %f |
  # Minify Javascript
  while read -r file; do

      # get last `.` occurence as starting extension
      extension=${file##*.}
      # filename (without 'last' extension)
      filename="${file%.*}"

      if [ "$extension" = 'js' ]
      then

        # minifiy with 'uglifyjs'
        uglifyjs -c --output /vagrant/interface/static/js/"$filename".min.js /vagrant/src/js/"$file"

      fi
  done
